### ISSUE TITLE
Cypress 9 compatibility?

### ISSUE THREAD

**Issue by Pomax** [component-driven/cypress-axe#114]
Cypress 9.x has been out for a few weeks,  would it be possible to update the version requirement for cypress-axe? (if it's compatible, of course)

**Comment by SheaBelsky** [comment]
Potentially related pull request: https://github.com/component-driven/cypress-axe/pull/112

@sapegin After the New Year, is this something you'd be able to look into? This is a blocking issue for projects on Node 16 or higher.

**Comment by sapegin** [comment]
Out in 0.14.0.
