### ISSUE TITLE
Update plugin to be compatible with Cypress 11

### ISSUE THREAD

**Issue by w3bdesign** [component-driven/cypress-axe#140]
It would be nice if this was updated to support Cypress 11.

**Comment by dolfbarr** [comment]
Changes list via migrating guide: https://docs.cypress.io/guides/references/migration-guide#Migrating-to-Cypress-version-10-0

**Comment by w3bdesign** [comment]
@dolfbarr 

I believe that is a migration guide for developers and not for plugin authors, but I may be mistaken.

I know Cypress released https://cypressdx.notion.site/Cypress-10-Plugin-Update-Guide-7474129c5a3b4cc7b969d1934c5844a0 when version 10 came out, but I am not sure if they have one for version 11 yet.

**Comment by javelinco** [comment]
When does the merged code end up in a released version?
