### ISSUE TITLE
Update axe-core to >= 3.5.0

### ISSUE THREAD

**Issue by DesselBane** [component-driven/cypress-axe#36]
Update the axe-core package to version <= 3.5.0 to include the 3.5 ruleset

**Comment by avanslaars** [comment]
I'll look at this when I find some time to properly test it. Hopefully soon.

**Comment by vanderhoop** [comment]
hey @avanslaars! Thanks for a great project. Curious if you're looking for help in the testing process in looking to upgrade to the 3.5 rule set? Were you thinking of manual tests, or adding some integration tests via actually executing Cypress? If so, I'd be happy to add a light CircleCI integration that asserts that the integration outputs violations, i.e. a _passing_ build on Circle would verify that exceptions are caught and the cypress build fails for the right reason. Lemmeknow!

**Comment by aldosuwandi** [comment]
@avanslaars is there any updates on this? Will it be helpful if I send a pull request for this change? I'd be happy to do it.

**Comment by hmniw** [comment]
> @avanslaars is there any updates on this? Will it be helpful if I send a pull request for this change? I'd be happy to do it.

Sounds like a pull request could be useful

**Comment by kristina-hager** [comment]
PR created: https://github.com/avanslaars/cypress-axe/pull/57

**Comment by kristina-hager** [comment]
Created a PR above.

**Comment by sapegin** [comment]
Let's keep all versioning discussions in #65.
