### ISSUE TITLE
Use axe.source instead of directly including node_modules

### ISSUE THREAD

**Issue by muraliavarma** [component-driven/cypress-axe#38]
In https://github.com/avanslaars/cypress-axe/blob/master/src/index.js#L3, I see that the file is directly loaded from `node_modules` using `fs`
I see that `axe-core` exposes a `source` parameter. Can that be used instead?
i.e.
```
import axe from 'axe-core';
export const injectAxe = () => {
  cy.window({ log: false }).then(window => {
    window.eval(axe.source)
  })
}
```
Is it a concern if it is unminified?

**Comment by avanslaars** [comment]
I was originally using the `source` property but it wasn't working for folks who were using webpack or TypeScript to build their bundle for testing. Bundling it this way resolved those issues. I'm happy to revisit it if I can verify that it works for the scenarios that were broken with the old setup.
