### ISSUE TITLE
With Cypress-Axe 0.8.1 commands not showing

### ISSUE THREAD

**Issue by SChathuranga** [component-driven/cypress-axe#42]
With 0.8.1 even after you add the import command to support/index.js the axe commands are not detected.
cy.injectAxe()
cy.injectAxe()
cy.checkA11y()

Those commands are not detected by cypress..

**Comment by sapegin** [comment]
This works for other users so without a repository that we can debug, we can't say much.

**Comment by cshouts-tasc** [comment]
@SChathuranga If you're using TypeScript, make sure to add the `@types/cypress-axe` package as a dev dependency.
