### ISSUE TITLE
Where can I find information on adding Custom Rules for aXe

### ISSUE THREAD

**Issue by kamal2222ahmed** [component-driven/cypress-axe#45]
axe-core has rules provided at https://github.com/dequelabs/axe-core/tree/develop/lib/rules
but could not find an example custom json to append custom rules. What I want to do is to manually test a site using Trusted Tester Test Process, and add the test to the custom list of tests with expected / actual type assertions, so as the custom tests grow in size the amount of time needed to test against trusted tester tests, manually is reduced.

**Comment by michaeljaltamirano** [comment]
@kamal2222ahmed I think passing in custom objects to the `rules` property of [`cy.configureAxe`](https://github.com/avanslaars/cypress-axe#cyconfigureaxe) might be what you want.
