### ISSUE TITLE
How do you exclude an element from checkA11y?

### ISSUE THREAD

**Issue by jemmrich** [component-driven/cypress-axe#55]
I am using these versions: 
```
    "axe-core": "4.0.1",
    "cypress": "4.11.0",
    "cypress-axe": "0.8.1",
```

Using this in my cypress test:
```
    cy.injectAxe();
    cy.checkA11y({
      exclude: [
        [['#onetrust-consent-sdk']]
      ]
    });
```

But getting these error:
```
SyntaxError
Failed to execute 'querySelectorAll' on 'Document': '[object Object]' is not a valid selector.
```

It seems like the first param for `checkA11y` should not be an object, yet looking at the documentation and examples here it should work:

* https://www.deque.com/axe/core-documentation/api-documentation/#context-parameter
* https://github.com/dequelabs/axe-core/blob/19cf29f5c59d79819a39cc51502b33c439111953/test/integration/full/context/context.js#L17

Any ideas? My goal is to ignore a11y checks for the div specified by an ID.

**Comment by stereobooster** [comment]
@jemmrich  Does exclude option works for you?

I tried following and no luck

```js
    cy.configureAxe({
      exclcude: [['button']] // [['[data-skipa11y]']]
    })
    cy.checkA11y({
      include: cy.window({ log: false }),
      exclcude: ['button']
    })
```

**Comment by stereobooster** [comment]
There was a typo in word `exclude` 🤦‍♀️

**Comment by karithomas** [comment]
@jemmrich I'm trying to exclude the onetrust banner right now as well.  Could you tell me how you managed that?  Here is what I have but it's still throwing the aria-dialog-name issue despite the exclude existing:

```javascript
cy.injectAxe()
            cy.checkA11y(null, {
                exclude: [['#onetrust-consent-sdk']],
                includedImpacts: ['critical', 'serious'],
                rules: {
                    'frame-title': { enabled: false }
                }
            })
        })
```

**Comment by mjpoo** [comment]
> @jemmrich I'm trying to exclude the onetrust banner right now as well. Could you tell me how you managed that? Here is what I have but it's still throwing the aria-dialog-name issue despite the exclude existing:
> 
> ```js
> cy.injectAxe()
>             cy.checkA11y(null, {
>                 exclude: [['#onetrust-consent-sdk']],
>                 includedImpacts: ['critical', 'serious'],
>                 rules: {
>                     'frame-title': { enabled: false }
>                 }
>             })
>         })
> ```

@karithomas I suspect it is because you have a nested array. 
You could try changing the `exclude` line to:

```
exclude: ['#onetrust-consent-sdk'],
```

**Comment by demenech** [comment]
Hey.
I managed to get it to work with the following syntax:
``` 
cy.checkA11y({
    exclude: [
      ['.flDebugTimerPanel'], 
      ['.flDebugTemplatePanel'], 
      ['.flDebugLoggingPanel'], 
      ['.flDebugRouteListPanel'], 
      ['.flDebugProfilerPanel'], 
    ]}, 
    { ... }
)
```

My deps:
```
    "axe-core": "^4.5.2",
    "cypress-axe": "^0.14.0",
```
