### ISSUE TITLE
Need to upgrade to axe-core 4.0.1

### ISSUE THREAD

**Issue by vnorekyan** [component-driven/cypress-axe#58]
As mentioned [here](https://www.deque.com/blog/announcing-axe-core-4-0/), the latest version of axe-core fixes a CSP issue where injectAxe() doesn't work with a strict content security policy that doesn't allow unsafe-eval for scripts. 

I'll submit a PR for this.

**Comment by sapegin** [comment]
Let's keep all versioning discussions in #65.
