### ISSUE TITLE
Allow users to use any version of axe core

### ISSUE THREAD

**Issue by aldosuwandi** [component-driven/cypress-axe#65]
I see a couple of issues opened to upgrade axe core version, which is bundled in this library. (https://github.com/avanslaars/cypress-axe/issues/36, https://github.com/avanslaars/cypress-axe/issues/58)

To avoid this type of request in the future, I think we can make this awesome library more flexible by allowing users to use any axe core version.

I'm proposing to add a parameter to the injectAxe method, so users can specify their axe core source/version to overwrite the default version. 

Sample scenario: Assuming the user wants to use the latest axe core
1. Install the latest axe-core
```
npm install -D axe-core@latest
```
2. Load axe.min.js and pass it into the injectAxe method
```
cy.readFile('node_modules/axe-core/axe.min.js', 'utf-8').then((content) => {
    cy.injectAxe(content);
    cy.checkA11y();
})
```

**Comment by sapegin** [comment]
I might be missing something but axe-core is a peer dependency already, so it allows you to install and use any 3.x or 4.x version. What am I missing here?

https://github.com/component-driven/cypress-axe/blob/61631c14a0190329cebc8f8ac9e8f81f1f1ce071/package.json#L19-L21

**Comment by cshouts-tasc** [comment]
It seems like npm has already solved this problem. Make `axe-core` a peer dependency and everything will work as intended with the developers preferred version of `axe-core` without any additional setup on their end.

Current consumers of the package should be able to continue using `cy.injectAxe()` and `cy.configureAxe()` in the same way they do today.

**Comment by aldosuwandi** [comment]
Currently, axe-core is bundled within this library, so unless we change the build setup, the peer dependency approach won't work.
see: https://github.com/component-driven/cypress-axe/issues/37#issue-612195722

The proposed solution should work if we decide to keep the bundled approach. But, if we want to unbundle it; then, peer dependency should be enough.

**Comment by sapegin** [comment]
Now I see the problem! It's bundling all dependencies, which doesn't sound like an optimal solution:

https://github.com/component-driven/cypress-axe/blob/ca7ac69eaa78d0fa0108bae2eb48bbca916e49ce/package.json#L13

And looks like there were reasons to bundle it though I'm not sure what exactly was the problem:

https://github.com/component-driven/cypress-axe/issues/37#issuecomment-625419673

**Comment by sapegin** [comment]
I've done some experiments on my project that uses cypress-axe.

When I try to use not bundled code, it fails with “fs.readFileSync is not a function”:

![image](https://user-images.githubusercontent.com/70067/97266783-5a248280-1829-11eb-8ef4-59903d05f9e7.png)

However, using `axe.source` as suggested in #38 works fine.

I suggest we make a version with `axe.source` without bundling and see what other problems folks may have.

**Comment by sapegin** [comment]
I've opened a pull request #69 — this works perfectly in my project. Would be great if anyone else could test it too.

**Comment by aldosuwandi** [comment]
Thanks, @sapegin. I'm not sure either why @avanslaars decided to bundle it. If we can unbundle it, that will be great.
I tried PR https://github.com/component-driven/cypress-axe/pull/69 in my project and found an issue. Please see my comment [here](https://github.com/component-driven/cypress-axe/pull/69#discussion_r512576666).
