### ISSUE TITLE
exports is not defined on v0.9.1

### ISSUE THREAD

**Issue by candiii-lin** [component-driven/cypress-axe#71]
Getting this error when using 0.9.1 with axe-core 4.0.2 as a peer dependencies
```
ReferenceError: exports is not defined
      at axeFunction (eval at <anonymous> (http://172.25.25.197:3000/__cypress/tests?p=cypress/support/index.js), <anonymous>:24:14)
      at eval (eval at <anonymous> (http://172.25.25.197:3000/__cypress/tests?p=cypress/support/index.js), <anonymous>:27630:3)
      at eval (<anonymous>)
```

**Comment by aldosuwandi** [comment]
did you get this error with cypress 5? I think this module isn't compatible with cypress 5 yet.
ref: https://github.com/component-driven/cypress-axe/issues/56

**Comment by markgaze** [comment]
I get this using Cypress v5.5 so I assume it is the same issue as in #56

**Comment by candiii-lin** [comment]
> did you get this error with cypress 5? I think this module isn't compatible with cypress 5 yet.
> ref: #56

I did. I am using Cypress v5.5. Currently just pinning my version to 0.8.1 so that I can continue to use this module.

**Comment by sapegin** [comment]
Closing as a duplicate of #56.
