### ISSUE TITLE
cannot resolve axe-core/axe.min.js

### ISSUE THREAD

**Issue by An-AngryBear** [component-driven/cypress-axe#74]
suddenly getting this error with no changes to my code. Using version 0.10.0:

have tried deleting dist and node_modules folder, running `npm run update` and built new dist

`Module not found: Error: Can't resolve 'axe-core/axe.min.js' in /path/node_modules/cypress-axe/dist`

**Comment by An-AngryBear** [comment]
apparently I needed to add axe-core as a dependency... wonder why that would just pop up now.. closing

**Comment by sapegin** [comment]
axe-core was bundled in the previous versions. We may probably better handle errors here.
