### ISSUE TITLE
update to support Cypress 7

### ISSUE THREAD

**Issue by Pomax** [component-driven/cypress-axe#96]
Cypress is on 7.2.0 by now, it would be very useful if this package could be updated to support that (it's currently set to ^6)

**Comment by Develliot** [comment]
+1 this we now at cypress 7.3

**Comment by mathiashellsing** [comment]
cypress@7.4.0 now

**Comment by rkristelijn** [comment]
We have cypress@7.2 installed, seems to work most of the time however we get this error in the after each hook:

```
TypeError: Cannot read property 'level' of undefined
```

The only things I can find in the code of cypress itself is log.level. Just wondering if someone ran into the same issue

**Comment by Pomax** [comment]
that sounds like a separate issue and probably deserves getting filed as new issue - this one's specifically about updating the dependency entry to explicitly cover 7.x

**Comment by rkristelijn** [comment]
@Pomax thanks for the feedback, I'm unable to reproduce on an empty boilerplate https://github.com/rkristelijn/cypress-7-axe 

Cypress-axe seem to work ok-ish with imports directly in the test file

**Comment by ben-reitz** [comment]
Hey @rkristelijn - we've been facing the same problem. It's only intermittent for us for some reason. Might be worth raising a separate issues for it. We were seeing it with cypress v6 too, although it seems to happen much more frequently with v7 🤷🏼
